### ISSUE TITLE
GM_addStyle is not defined

### ISSUE THREAD

**Issue by lundmikkel** [x-inkfish-x/DuolingoUserscripts#5]
I seem to get errors for all the user scripts due to a GM_addStyle method missing:
<img width="1431" alt="errors" src="https://user-images.githubusercontent.com/1230950/49865273-ce580780-fe04-11e8-9eb5-cddc147bfc4a.png">

**Comment by x-inkfish-x** [comment]
I had that issue in the beginning, but not any more. Do you still have it? If you do, are you using Tampermonkey or Greasemonkey?

Edit: Sorry for not getting to this sooner btw, I've been fairly busy recently and haven't had time to keep track of this project

**Comment by lundmikkel** [comment]
It's been a while, but I think I had the problem in Greasemonkey, but not in Tampermonkey.

**Comment by x-inkfish-x** [comment]
It took me longer than it should have, but hopefully this issue is now fixed. I've replaced the GM_addStyle method with my own plain JavaScript method, which should work no matter how you run your userscripts (within reason)
