### ISSUE TITLE
Helper class outdated

### ISSUE THREAD

**Issue by camilstaps** [x-inkfish-x/DuolingoUserscripts#7]
I'm having some trouble getting the Strength Viewer to work. It seems that in the helper class, the following classes are outdated:

- `skillElementClass` should be `_2iiJH`
- `getSkillForElement` should search for `_2MxuB`

However, even with those changes the result of `findReactElement` is `null`. Apparently, the `__reactInternalInstance` key is not present yet at this stage. Perhaps the operation needs to be delayed? Perhaps the mutation observer can be changed to watch for when the react key is added instead of when the element is added?

**Comment by x-inkfish-x** [comment]
Thanks for reaching out to me about this, I hadn't noticed! Also, sorry for taking so long to get back to you.
I have updated `skillElementClass` and `getSkillForElement` to use the new classes (and, for `getSkillElement`, access the data in a new way, so maybe there has been a change there), and that appears to have solved the issue. However, when switching languages not all skills are coming through. I'm not sure why, but will try to look into it/an alternative method when I have time.

As for changing the way the mutation observer works, I'm not sure, honestly. JS is not really my expertise, but, once again, it's something I may look into.

Hope that this fixes your issue, and, once again, sorry for taking so long getting back to you!

**Comment by camilstaps** [comment]
Thanks, @x-inkfish-x, and don't worry about taking some time to answer. I have installed the new version, but it doesn't seem to work for me yet. The result of `findReactElement` is still `null` (I did check that the classes are still the same.)

By the way, perhaps instead of classes you could use the `data-test="skill"` attribute that appears to be present on the nodes you want to have. These can be found using `querySelectorAll` (https://stackoverflow.com/a/16775485). That doesn't solve the current problem, but hopefully it's more stable than searching for the class name.

**Comment by camilstaps** [comment]
Closing because I don't use this anymore and would like to clean up my issue list. See #10 for a similar issue.
